DROP DATABASE IF EXISTS TestDB;
CREATE DATABASE TestDB;

USE TestDB;

CREATE TABLE TestTable (
	ID INT(3) AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    JOB_POSITION VARCHAR(10) NOT NULL,
    CHECK (JOB_POSITION IN ("Customer", "Employee", "Administrator"))
);

INSERT INTO TestTable(FIRST_NAME, LAST_NAME, JOB_POSITION) VALUES ("Bill", "Board", "Employee");

SELECT * FROM TestTable;

DROP USER "A001";

CREATE USER "A001" IDENTIFIED BY "1234";

GRANT SELECT
ON testtable
TO "A001"@"localhost";

FLUSH PRIVILEGES;