DROP DATABASE IF EXISTS TestDB;
CREATE DATABASE TestDB;

USE TestDB;

CREATE TABLE TestTable (
	ID INT(3) AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    JOB_POSITION VARCHAR(10) NOT NULL,
    CHECK (JOB_POSITION IN ("Customer", "Employee", "Administrator"))
);

INSERT INTO TestTable(FIRST_NAME, LAST_NAME, JOB_POSITION) VALUES ("Bill", "Board", "Employee"),
("Jane", "Doe", "Customer");

DROP USER IF EXISTS "001"@"localhost";

CREATE USER "001"@"localhost" IDENTIFIED BY "1234";

GRANT SELECT
ON testdb.testtable
TO "001"@"localhost";

CREATE USER "002"@"localhost" IDENTIFIED BY "1234";

GRANT SELECT
ON testdb.testtable
TO "002"@"localhost";

SELECT JOB_POSITION FROM TestDB.TestTable WHERE LPAD(ID, 3, 0) = "001";